#设置环境
spring:
  profiles:
    include: local


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${host.database.ip}:3306/westtext?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: ${host.database.pwd}

  jackson:
    default-property-inclusion: non_null

  main:
    allow-circular-references: true  #允许循环引用

  data:
    redis:
      host: ${host.redis.ip}
      port: 6379
      password: ${host.redis.pwd}

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
  tomcat:
    max-swallow-size: 100


mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl






